#ifndef DUAL_ARM_V2_2_GRIPPER_CONFIG_H
#define DUAL_ARM_V2_2_GRIPPER_CONFIG_H

// Physical connection. CUARM_GRIPPER_ARM_INDEX: 0 = left arm, 2 = right arm.
#define CUARM_GRIPPER_ARM_INDEX 0
#define CUARM_GRIPPER_CAN_DEVICE_TYPE 4U  // VCI_USBCAN2
#define CUARM_GRIPPER_CAN_DEVICE_INDEX 0
#define CUARM_GRIPPER_CAN_CHANNEL 0
#define CUARM_GRIPPER_MOTOR_TYPE 3       // RMD_V4
#define CUARM_GRIPPER_MOTOR_ID 8
#define CUARM_GRIPPER_GEAR_RATIO 10.0F
#define CUARM_GRIPPER_ENCODER_RESOLUTION 16384
#define CUARM_GRIPPER_DIRECTION 1

// Calibrated output-shaft positions.
#define CUARM_GRIPPER_OPEN_POSITION_DEG (-67.095001F)
#define CUARM_GRIPPER_CLOSE_POSITION_DEG 5.132000F
#define CUARM_GRIPPER_POSITION_TOLERANCE_DEG 0.25F

// Public SDK ranges and physical full-scale mappings.
#define CUARM_GRIPPER_POSITION_MIN 0U
#define CUARM_GRIPPER_POSITION_MAX 1000U
#define CUARM_GRIPPER_SPEED_MIN 1U
#define CUARM_GRIPPER_SPEED_MAX 1000U
#define CUARM_GRIPPER_SPEED_MAX_DEG_S 360.0F
#define CUARM_GRIPPER_SLOWDOWN_ANGLE_DEG 10.0F
#define CUARM_GRIPPER_ACCELERATION_DEG_S2 360.0F
#define CUARM_GRIPPER_FORCE_MIN 1U
#define CUARM_GRIPPER_FORCE_MAX 1000U
#define CUARM_GRIPPER_FORCE_MAX_NM 1.0F

#define CUARM_GRIPPER_DEFAULT_SPEED 200U
#define CUARM_GRIPPER_DEFAULT_FORCE 500U
#define CUARM_GRIPPER_FORCE_CONFIRM_SAMPLES 3

#endif
